In [4]:
import torch
torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1))


True

In [5]:
x = torch.empty(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
x = torch.tensor([5,5, 3])
print(x)

tensor([[-1.6722e-15,  0.0000e+00,  1.3593e-43],
        [ 0.0000e+00,  1.6817e-05,  0.0000e+00],
        [-1.8709e-27,  1.7796e-43,  6.8938e+16],
        [ 0.0000e+00,  9.1084e-44,  0.0000e+00],
        [ 1.6817e-05,  0.0000e+00, -1.8709e-27]])
tensor([[0.6123, 0.5659, 0.0039],
        [0.6128, 0.4336, 0.6287],
        [0.4090, 0.0536, 0.9688],
        [0.6705, 0.0725, 0.4474],
        [0.9811, 0.2449, 0.0848]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5, 5, 3])
